/* The following code was generated by JFlex 1.6.1 */

package scanner;
import static scanner.Token.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Gaby/Desktop/JFlexScanner/JFlexScanner/src/scanner/scanner.flex</tt>
 */
class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\3\1\4\1\4\1\4\22\0\1\3\6\0\1\0"+
    "\1\34\1\36\3\0\1\35\1\0\1\0\12\2\7\0\32\1\4\0"+
    "\1\0\1\0\1\5\1\12\1\21\1\7\1\13\1\26\1\14\1\23"+
    "\1\15\1\1\1\32\1\17\1\30\1\6\1\16\1\31\1\1\1\10"+
    "\1\22\1\20\1\27\1\24\1\25\1\33\1\11\1\1\12\0\1\4"+
    "\u1fa2\0\1\4\1\4\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\24\2\1\1\5\2"+
    "\1\5\7\2\1\6\1\7\1\10\1\11\4\2\1\12"+
    "\24\2\1\0\1\13\1\2\1\14\1\15\1\16\7\2"+
    "\1\17\3\2\1\20\10\2\1\21\2\2\1\22\5\2"+
    "\1\23\2\2\1\24\2\2\1\25\1\0\2\2\1\26"+
    "\1\27\2\2\1\30\2\2\1\31\1\32\3\2\1\33"+
    "\1\34\1\35\1\36\1\2\1\37\3\2\1\40\2\2"+
    "\1\41\6\2\1\3\1\42\3\2\1\43\2\2\1\44"+
    "\1\2\1\45\2\2\1\46\1\47\1\50\2\2\1\51"+
    "\3\2\1\52\1\53\1\54\1\2\1\55\1\2\1\56"+
    "\3\2\1\57\2\2\1\60\1\61\1\2\1\62\1\2"+
    "\1\63\1\2\1\64\1\65\1\2\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[190];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\37\0\76\0\135\0\37\0\174\0\233\0\272"+
    "\0\331\0\370\0\u0117\0\u0136\0\u0155\0\u0174\0\u0193\0\u01b2"+
    "\0\u01d1\0\u01f0\0\u020f\0\u022e\0\u024d\0\u026c\0\u028b\0\u02aa"+
    "\0\u02c9\0\u02e8\0\u0307\0\u0326\0\u0345\0\u0364\0\u0383\0\u03a2"+
    "\0\u03c1\0\u03e0\0\u03ff\0\u041e\0\u043d\0\u045c\0\u047b\0\u049a"+
    "\0\76\0\76\0\76\0\u04b9\0\u04d8\0\u04f7\0\u0516\0\76"+
    "\0\u0535\0\u0554\0\u0573\0\u0592\0\u05b1\0\u05d0\0\u05ef\0\u060e"+
    "\0\u062d\0\u064c\0\u066b\0\u068a\0\u06a9\0\u06c8\0\u06e7\0\u0706"+
    "\0\u0725\0\u0744\0\u0763\0\u0782\0\u07a1\0\76\0\u07c0\0\76"+
    "\0\76\0\76\0\u07df\0\u07fe\0\u081d\0\u083c\0\u085b\0\u087a"+
    "\0\u0899\0\76\0\u08b8\0\u08d7\0\u08f6\0\76\0\u0915\0\u0934"+
    "\0\u0953\0\u0972\0\u0991\0\u09b0\0\u09cf\0\u09ee\0\76\0\u0a0d"+
    "\0\u0a2c\0\76\0\u0a4b\0\u0a6a\0\u0a89\0\u0aa8\0\u0ac7\0\u0ae6"+
    "\0\u0b05\0\u0b24\0\76\0\u0b43\0\u0b62\0\76\0\u0b81\0\u0ba0"+
    "\0\u0bbf\0\76\0\76\0\u0bde\0\u0bfd\0\76\0\u0c1c\0\u0c3b"+
    "\0\76\0\76\0\u0c5a\0\u0c79\0\u0c98\0\76\0\76\0\76"+
    "\0\76\0\u0cb7\0\76\0\u0cd6\0\u0cf5\0\u0d14\0\76\0\u0d33"+
    "\0\u0d52\0\76\0\u0d71\0\u0d90\0\u0daf\0\u0dce\0\u0ded\0\u0e0c"+
    "\0\37\0\76\0\u0e2b\0\u0e4a\0\u0e69\0\76\0\u0e88\0\u0ea7"+
    "\0\76\0\u0ec6\0\76\0\u0ee5\0\u0f04\0\76\0\76\0\76"+
    "\0\u0f23\0\u0f42\0\76\0\u0f61\0\u0f80\0\u0f9f\0\76\0\76"+
    "\0\76\0\u0fbe\0\76\0\u0fdd\0\76\0\u0ffc\0\u101b\0\u103a"+
    "\0\76\0\u1059\0\u1078\0\76\0\76\0\u1097\0\76\0\u10b6"+
    "\0\76\0\u10d5\0\76\0\76\0\u10f4\0\76";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[190];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\0\1\6\1\7\1\10"+
    "\1\11\1\3\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\3\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\3\1\31\1\32\2\2\40\0\2\3"+
    "\2\0\27\3\5\0\1\4\35\0\2\3\2\0\1\3"+
    "\1\33\1\3\1\34\23\3\4\0\2\3\2\0\10\3"+
    "\1\35\1\36\15\3\4\0\2\3\2\0\10\3\1\37"+
    "\1\40\15\3\4\0\2\3\2\0\6\3\1\41\20\3"+
    "\4\0\2\3\2\0\4\3\1\42\1\3\1\43\2\3"+
    "\1\44\15\3\4\0\2\3\2\0\1\3\1\45\10\3"+
    "\1\46\14\3\4\0\2\3\2\0\11\3\1\47\15\3"+
    "\4\0\2\3\2\0\1\3\1\50\17\3\1\51\5\3"+
    "\4\0\2\3\2\0\3\3\1\52\15\3\1\53\5\3"+
    "\4\0\2\3\2\0\1\54\10\3\1\55\15\3\4\0"+
    "\2\3\2\0\3\3\1\56\1\57\4\3\1\60\4\3"+
    "\1\61\10\3\4\0\2\3\2\0\1\62\10\3\1\63"+
    "\4\3\1\64\10\3\4\0\2\3\2\0\6\3\1\65"+
    "\4\3\1\66\2\3\1\67\10\3\4\0\2\3\2\0"+
    "\1\70\26\3\4\0\2\3\2\0\3\3\1\71\4\3"+
    "\1\72\5\3\1\73\10\3\4\0\2\3\2\0\1\74"+
    "\7\3\1\75\1\76\10\3\1\77\4\3\4\0\2\3"+
    "\2\0\1\3\1\100\25\3\4\0\2\3\2\0\11\3"+
    "\1\101\15\3\4\0\2\3\2\0\1\102\2\3\1\103"+
    "\23\3\4\0\2\3\2\0\11\3\1\104\15\3\40\0"+
    "\1\105\2\0\2\3\2\0\2\3\1\106\24\3\4\0"+
    "\2\3\2\0\3\3\1\107\23\3\4\0\2\3\2\0"+
    "\12\3\1\110\14\3\4\0\2\3\2\0\13\3\1\111"+
    "\13\3\4\0\2\3\2\0\17\3\1\112\7\3\4\0"+
    "\2\3\2\0\20\3\1\113\6\3\4\0\2\3\2\0"+
    "\1\114\13\3\1\115\7\3\1\116\2\3\4\0\2\3"+
    "\2\0\13\3\1\117\13\3\4\0\2\3\2\0\7\3"+
    "\1\120\17\3\4\0\2\3\2\0\11\3\1\121\15\3"+
    "\4\0\2\3\2\0\2\3\1\122\24\3\4\0\2\3"+
    "\2\0\15\3\1\123\11\3\4\0\2\3\2\0\13\3"+
    "\1\124\13\3\4\0\2\3\2\0\12\3\1\125\1\126"+
    "\13\3\4\0\2\3\2\0\5\3\1\127\21\3\4\0"+
    "\2\3\2\0\1\3\1\130\25\3\4\0\2\3\2\0"+
    "\22\3\1\131\4\3\4\0\2\3\2\0\24\3\1\132"+
    "\2\3\4\0\2\3\2\0\6\3\1\133\20\3\4\0"+
    "\2\3\2\0\15\3\1\134\11\3\4\0\2\3\2\0"+
    "\1\3\1\135\25\3\4\0\2\3\2\0\1\136\26\3"+
    "\4\0\2\3\2\0\13\3\1\137\13\3\4\0\2\3"+
    "\2\0\3\3\1\140\23\3\4\0\2\3\2\0\11\3"+
    "\1\141\15\3\4\0\2\3\2\0\3\3\1\142\23\3"+
    "\4\0\2\3\2\0\10\3\1\143\16\3\4\0\2\3"+
    "\2\0\13\3\1\144\13\3\4\0\2\3\2\0\10\3"+
    "\1\145\16\3\4\0\2\3\2\0\12\3\1\146\14\3"+
    "\4\0\2\3\2\0\12\3\1\147\14\3\4\0\2\3"+
    "\2\0\3\3\1\150\23\3\4\0\2\3\2\0\1\3"+
    "\1\151\25\3\4\0\2\3\2\0\13\3\1\152\13\3"+
    "\4\0\2\3\2\0\2\3\1\153\24\3\4\0\2\3"+
    "\2\0\14\3\1\154\12\3\4\0\2\3\2\0\11\3"+
    "\1\155\15\3\4\0\2\3\2\0\3\3\1\156\23\3"+
    "\5\0\1\157\35\0\2\3\2\0\1\160\26\3\4\0"+
    "\2\3\2\0\1\3\1\161\25\3\4\0\2\3\2\0"+
    "\2\3\1\162\7\3\1\163\14\3\4\0\2\3\2\0"+
    "\11\3\1\164\15\3\4\0\2\3\2\0\6\3\1\165"+
    "\20\3\4\0\2\3\2\0\6\3\1\166\20\3\4\0"+
    "\2\3\2\0\10\3\1\167\16\3\4\0\2\3\2\0"+
    "\12\3\1\170\14\3\4\0\2\3\2\0\6\3\1\171"+
    "\20\3\4\0\2\3\2\0\11\3\1\172\15\3\4\0"+
    "\2\3\2\0\10\3\1\173\16\3\4\0\2\3\2\0"+
    "\6\3\1\174\20\3\4\0\2\3\2\0\7\3\1\175"+
    "\17\3\4\0\2\3\2\0\6\3\1\176\20\3\4\0"+
    "\2\3\2\0\6\3\1\177\20\3\4\0\2\3\2\0"+
    "\1\3\1\200\25\3\4\0\2\3\2\0\6\3\1\201"+
    "\20\3\4\0\2\3\2\0\15\3\1\202\11\3\4\0"+
    "\2\3\2\0\3\3\1\203\23\3\4\0\2\3\2\0"+
    "\10\3\1\204\16\3\4\0\2\3\2\0\3\3\1\205"+
    "\23\3\4\0\2\3\2\0\13\3\1\206\13\3\4\0"+
    "\2\3\2\0\16\3\1\207\10\3\4\0\2\3\2\0"+
    "\12\3\1\210\14\3\4\0\2\3\2\0\15\3\1\211"+
    "\11\3\4\0\2\3\2\0\6\3\1\212\20\3\4\0"+
    "\2\3\2\0\20\3\1\213\6\3\4\0\2\3\2\0"+
    "\14\3\1\214\12\3\4\0\2\3\2\0\10\3\1\215"+
    "\16\3\4\0\2\3\2\0\25\3\1\216\1\3\4\0"+
    "\2\3\2\0\7\3\1\217\4\3\1\220\12\3\5\0"+
    "\1\157\33\0\1\221\1\0\2\3\2\0\4\3\1\222"+
    "\22\3\4\0\2\3\2\0\13\3\1\223\13\3\4\0"+
    "\2\3\2\0\3\3\1\224\23\3\4\0\2\3\2\0"+
    "\1\225\26\3\4\0\2\3\2\0\1\3\1\226\25\3"+
    "\4\0\2\3\2\0\6\3\1\227\20\3\4\0\2\3"+
    "\2\0\1\3\1\230\25\3\4\0\2\3\2\0\12\3"+
    "\1\231\14\3\4\0\2\3\2\0\10\3\1\232\16\3"+
    "\4\0\2\3\2\0\13\3\1\233\13\3\4\0\2\3"+
    "\2\0\1\3\1\234\25\3\4\0\2\3\2\0\13\3"+
    "\1\235\13\3\4\0\2\3\2\0\6\3\1\236\20\3"+
    "\4\0\2\3\2\0\6\3\1\237\20\3\4\0\2\3"+
    "\2\0\6\3\1\240\20\3\4\0\2\3\2\0\1\241"+
    "\26\3\4\0\2\3\2\0\13\3\1\242\13\3\4\0"+
    "\2\3\2\0\12\3\1\243\14\3\4\0\2\3\2\0"+
    "\6\3\1\244\20\3\4\0\2\3\2\0\3\3\1\245"+
    "\23\3\4\0\2\3\2\0\6\3\1\246\20\3\4\0"+
    "\2\3\2\0\11\3\1\247\15\3\4\0\2\3\2\0"+
    "\2\3\1\250\24\3\4\0\2\3\2\0\13\3\1\251"+
    "\13\3\4\0\2\3\2\0\1\252\26\3\4\0\2\3"+
    "\2\0\6\3\1\253\20\3\4\0\2\3\2\0\1\3"+
    "\1\254\25\3\4\0\2\3\2\0\7\3\1\255\17\3"+
    "\4\0\2\3\2\0\10\3\1\256\16\3\4\0\2\3"+
    "\2\0\3\3\1\257\23\3\4\0\2\3\2\0\10\3"+
    "\1\260\16\3\4\0\2\3\2\0\2\3\1\261\24\3"+
    "\4\0\2\3\2\0\1\262\26\3\4\0\2\3\2\0"+
    "\2\3\1\263\24\3\4\0\2\3\2\0\1\3\1\264"+
    "\25\3\4\0\2\3\2\0\13\3\1\265\13\3\4\0"+
    "\2\3\2\0\1\3\1\266\25\3\4\0\2\3\2\0"+
    "\2\3\1\267\24\3\4\0\2\3\2\0\11\3\1\270"+
    "\15\3\4\0\2\3\2\0\23\3\1\271\3\3\4\0"+
    "\2\3\2\0\22\3\1\272\4\3\4\0\2\3\2\0"+
    "\13\3\1\273\13\3\4\0\2\3\2\0\1\3\1\274"+
    "\25\3\4\0\2\3\2\0\3\3\1\275\23\3\4\0"+
    "\2\3\2\0\6\3\1\276\20\3\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4371];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\77\1\1\0\51\1\1\0"+
    "\41\1\1\11\55\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[190];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
        public String lexeme;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 140) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return ERROR;
            }
          case 55: break;
          case 2: 
            { lexeme=yytext(); 
                                return ID;
            }
          case 56: break;
          case 3: 
            { lexeme=yytext(); 
                                return INT;
            }
          case 57: break;
          case 4: 
            { /*Ignore*/
            }
          case 58: break;
          case 5: 
            { return DO;
            }
          case 59: break;
          case 6: 
            { return IN;
            }
          case 60: break;
          case 7: 
            { return IF;
            }
          case 61: break;
          case 8: 
            { return OR;
            }
          case 62: break;
          case 9: 
            { return OF;
            }
          case 63: break;
          case 10: 
            { return TO;
            }
          case 64: break;
          case 11: 
            { return AND;
            }
          case 65: break;
          case 12: 
            { return NIL;
            }
          case 66: break;
          case 13: 
            { return NOT;
            }
          case 67: break;
          case 14: 
            { return DIV;
            }
          case 68: break;
          case 15: 
            { return END;
            }
          case 69: break;
          case 16: 
            { return INT;
            }
          case 70: break;
          case 17: 
            { return SET;
            }
          case 71: break;
          case 18: 
            { return VAR;
            }
          case 72: break;
          case 19: 
            { return FOR;
            }
          case 73: break;
          case 20: 
            { return MOD;
            }
          case 74: break;
          case 21: 
            { return XOR;
            }
          case 75: break;
          case 22: 
            { return READ;
            }
          case 76: break;
          case 23: 
            { return REAL;
            }
          case 77: break;
          case 24: 
            { return BYTE;
            }
          case 78: break;
          case 25: 
            { return ELSE;
            }
          case 79: break;
          case 26: 
            { return GOTO;
            }
          case 80: break;
          case 27: 
            { return TRUE;
            }
          case 81: break;
          case 28: 
            { return TYPE;
            }
          case 82: break;
          case 29: 
            { return THEN;
            }
          case 83: break;
          case 30: 
            { return CASE;
            }
          case 84: break;
          case 31: 
            { return CHAR;
            }
          case 85: break;
          case 32: 
            { return WITH;
            }
          case 86: break;
          case 33: 
            { return FILE;
            }
          case 87: break;
          case 34: 
            { return ARRAY;
            }
          case 88: break;
          case 35: 
            { return BEGIN;
            }
          case 89: break;
          case 36: 
            { return LABEL;
            }
          case 90: break;
          case 37: 
            { return CONST;
            }
          case 91: break;
          case 38: 
            { return WRITE;
            }
          case 92: break;
          case 39: 
            { return WHILE;
            }
          case 93: break;
          case 40: 
            { return FALSE;
            }
          case 94: break;
          case 41: 
            { return UNTIL;
            }
          case 95: break;
          case 42: 
            { return DOWNTO;
            }
          case 96: break;
          case 43: 
            { return RECORD;
            }
          case 97: break;
          case 44: 
            { return REPEAT;
            }
          case 98: break;
          case 45: 
            { return INLINE;
            }
          case 99: break;
          case 46: 
            { return STRING;
            }
          case 100: break;
          case 47: 
            { return PACKED;
            }
          case 101: break;
          case 48: 
            { return BOOLEAN;
            }
          case 102: break;
          case 49: 
            { return LONGINT;
            }
          case 103: break;
          case 50: 
            { return FORWARD;
            }
          case 104: break;
          case 51: 
            { return PROGRAM;
            }
          case 105: break;
          case 52: 
            { return SHORTINT;
            }
          case 106: break;
          case 53: 
            { return FUNCTION;
            }
          case 107: break;
          case 54: 
            { return PROCEDURE;
            }
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
