
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 11 00:23:42 CST 2016
//----------------------------------------------------

package scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_RESTA = 4;
  public static final int OP_SUMA = 3;
  public static final int ENTERO = 8;
  public static final int OP_MULT = 5;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PARENIZQ = 6;
  public static final int REAL = 9;
  public static final int error = 1;
  public static final int PARENDER = 7;
}

