
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package scanner;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_MENOR = 59;
  public static final int OP_DIVISION = 65;
  public static final int IDENTIFICADOR = 81;
  public static final int REAL = 83;
  public static final int PR_FOR = 21;
  public static final int PR_TO = 38;
  public static final int TIPO_ARRAY = 2;
  public static final int PR_TRUE = 39;
  public static final int OP_MENORMENORIGUAL = 79;
  public static final int OP_PUNTO = 71;
  public static final int PR_FORWARD = 22;
  public static final int OP_MENORMENOR = 78;
  public static final int OP_MULT = 64;
  public static final int PR_PROGRAM = 33;
  public static final int TIPO_STRING = 12;
  public static final int OP_MOD = 49;
  public static final int OP_MENOSIGUAL = 74;
  public static final int PARENTIZQ = 66;
  public static final int SEMI = 53;
  public static final int TIPO_CHAR = 5;
  public static final int TIPO_BOOLEAN = 3;
  public static final int TIPO_LONGINT = 8;
  public static final int PR_ELSE = 17;
  public static final int OP_SUMA = 62;
  public static final int PR_INLINE = 27;
  public static final int OP_RESTA = 63;
  public static final int PR_LABEL = 28;
  public static final int PR_FUNCTION = 23;
  public static final int OP_BRACKETDER = 69;
  public static final int PR_RECORD = 35;
  public static final int OP_MENOSMENOS = 55;
  public static final int PR_SET = 37;
  public static final int OP_DOSPUNTOS = 72;
  public static final int OP_MAYORIGUAL = 56;
  public static final int OP_DIV = 47;
  public static final int PR_END = 18;
  public static final int PR_PROCEDURE = 31;
  public static final int PR_DOWNTO = 16;
  public static final int PR_BEGIN = 13;
  public static final int PR_FILE = 20;
  public static final int ENTERO = 82;
  public static final int PR_CASE = 14;
  public static final int OP_MAYORMAYORIGUAL = 80;
  public static final int OP_MULTIGUAL = 75;
  public static final int TIPO_BYTE = 4;
  public static final int PR_REPEAT = 36;
  public static final int PR_WITH = 44;
  public static final int OP_MAYOR = 57;
  public static final int TIPO_NIL = 9;
  public static final int OP_DIVIGUAL = 76;
  public static final int PR_UNTIL = 41;
  public static final int OP_MENORMAYOR = 60;
  public static final int PR_DO = 15;
  public static final int PR_TYPE = 40;
  public static final int EOF = 0;
  public static final int OP_AND = 46;
  public static final int TIPO_REAL = 10;
  public static final int PR_READ = 34;
  public static final int OP_BRACKETIZQ = 68;
  public static final int PARENTDER = 67;
  public static final int OP_XOR = 51;
  public static final int TIPO_SHORTINT = 11;
  public static final int error = 1;
  public static final int OP_MASIGUAL = 73;
  public static final int PR_FALSE = 19;
  public static final int PR_VAR = 42;
  public static final int TIPO_CONST = 6;
  public static final int PR_IN = 26;
  public static final int TIPO_INT = 7;
  public static final int PR_IF = 25;
  public static final int PR_OF = 29;
  public static final int OP_IGUAL = 61;
  public static final int PR_PACKED = 30;
  public static final int STRING = 84;
  public static final int PR_THEN = 32;
  public static final int PR_GOTO = 24;
  public static final int OP_MAYORMAYOR = 77;
  public static final int PR_WRITE = 45;
  public static final int OP_COMA = 52;
  public static final int OP_DOSPUNTOSIGUAL = 70;
  public static final int OP_OR = 50;
  public static final int OP_MENORIGUAL = 58;
  public static final int PR_WHILE = 43;
  public static final int OP_NOT = 48;
  public static final int OP_SUMASUMA = 54;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TIPO_ARRAY",
  "TIPO_BOOLEAN",
  "TIPO_BYTE",
  "TIPO_CHAR",
  "TIPO_CONST",
  "TIPO_INT",
  "TIPO_LONGINT",
  "TIPO_NIL",
  "TIPO_REAL",
  "TIPO_SHORTINT",
  "TIPO_STRING",
  "PR_BEGIN",
  "PR_CASE",
  "PR_DO",
  "PR_DOWNTO",
  "PR_ELSE",
  "PR_END",
  "PR_FALSE",
  "PR_FILE",
  "PR_FOR",
  "PR_FORWARD",
  "PR_FUNCTION",
  "PR_GOTO",
  "PR_IF",
  "PR_IN",
  "PR_INLINE",
  "PR_LABEL",
  "PR_OF",
  "PR_PACKED",
  "PR_PROCEDURE",
  "PR_THEN",
  "PR_PROGRAM",
  "PR_READ",
  "PR_RECORD",
  "PR_REPEAT",
  "PR_SET",
  "PR_TO",
  "PR_TRUE",
  "PR_TYPE",
  "PR_UNTIL",
  "PR_VAR",
  "PR_WHILE",
  "PR_WITH",
  "PR_WRITE",
  "OP_AND",
  "OP_DIV",
  "OP_NOT",
  "OP_MOD",
  "OP_OR",
  "OP_XOR",
  "OP_COMA",
  "SEMI",
  "OP_SUMASUMA",
  "OP_MENOSMENOS",
  "OP_MAYORIGUAL",
  "OP_MAYOR",
  "OP_MENORIGUAL",
  "OP_MENOR",
  "OP_MENORMAYOR",
  "OP_IGUAL",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULT",
  "OP_DIVISION",
  "PARENTIZQ",
  "PARENTDER",
  "OP_BRACKETIZQ",
  "OP_BRACKETDER",
  "OP_DOSPUNTOSIGUAL",
  "OP_PUNTO",
  "OP_DOSPUNTOS",
  "OP_MASIGUAL",
  "OP_MENOSIGUAL",
  "OP_MULTIGUAL",
  "OP_DIVIGUAL",
  "OP_MAYORMAYOR",
  "OP_MENORMENOR",
  "OP_MENORMENORIGUAL",
  "OP_MAYORMAYORIGUAL",
  "IDENTIFICADOR",
  "ENTERO",
  "REAL",
  "STRING"
  };
}

